services:
  db:
    image: postgres:16
    container_name: bm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beautifulmind
    ports:
      - "5432:5432"
    volumes:
      - bm_pgdata:/var/lib/postgresql/data

volumes:
  bm_pgdata:
